add bdd testing
CSCI-GA-2820-SP24-003/recommendations pull request #53
Opened 2024-04-07 17:05 UTC by Ruochen1105

Changes:
  - Implemented `features/` for `behave`
  - Changed `.devcontainer/Dockerfile`
  - Included the BDD testing into `ci.yaml`

2024-04-09 16:53 UTC, huangiris17 commented
According to the homework requirement: "Create a .github/workflows/bdd.yml file". Should we have separate file for tdd and bdd test instead of one ci.yml?

2024-04-09 23:24 UTC, OlekKapera requested changes

2024-04-10 02:33 UTC, Ruochen1105 commented on .github/workflows/ci.yml
> +    container: rofrano/pipeline-selenium:latest
But we are using the `rofrano/pipeline-selenium:latest` image locally. Shouldn't we test with the same image?

2024-04-10 02:58 UTC, OlekKapera commented on .github/workflows/ci.yml
> +    container: rofrano/pipeline-selenium:latest
`rofrano/pipeline-selenium` is actually based out of `python:3.11-slim`. This means that it is almost identical to the local environment without all the unnecessary selenium stuff. However, I agree that our CI should match as closely as possible what we have locally. So you can keep it as is.

2024-04-10 02:59 UTC, OlekKapera approved these changes

2024-04-10 03:00 UTC, merged